database:
  DATABASE_HOST: database
  DATABASE_USER: quotesApp
  DATABASE_PASSWORD: senha
  DATABASE_NAME: quotesApp
  CLUSTER_IP_NAME: database
  CLUSTER_IP_PORT: 3306
  DEPLOYMENT_NAME: quotes-db-deployment
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_CONTAINER_PORT: 8080
  DEPLOYMENT_IMAGE_VERSION: "1.0"
  QUOTES_DB_PVC_NAME: quotes-db-pvc
  QUOTES_DB_PVC_STORAGE: 1Gi
  QUOTES_DB_VOLUME_NAME: quotes-db-pv
  QUOTES_DB_VOLUME_STORAGE: 1Gi
addget:
  NODEPORT_NAME: nodeport-addget-api #continuar
quotesapi:
  CLUSTER_IP_NAME: quotes-api #continuar
imagesapi:
  CLUSTER_IP_NAME: images-api #continuar
