database:
  CONFIGMAP_ENV:
  - name: DATABASE_HOST
    value: database
  - name: DATABASE_USER
    value: quotesApp
  - name: DATABASE_PASSWORD
    value: senha
  - name: DATABASE_NAME
    value: quotesApp
  CLUSTER_IP_NAME: database
  CLUSTER_IP_PORT: 3306
  DEPLOYMENT_NAME: quotes-db-deployment
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_CONTAINER_PORT: 8080
  DEPLOYMENT_IMAGE_VERSION: "1.0"
  DEPLOYMENT_LABELS:
  - name: app
    value: quotes-db
  QUOTES_DB_PVC_NAME: quotes-db-pvc
  QUOTES_DB_PVC_STORAGE: 1Gi
  QUOTES_DB_VOLUME_NAME: quotes-db-pv
  QUOTES_DB_VOLUME_STORAGE: 1Gi
addget:
  DEPLOYMENT_NAME: addget-api-deployment
  DEPLOYMENT_IMAGE_VERSION: "2.0"
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_CONTAINER_PORT: 8080
  DEPLOYMENT_CONTAINER_NAME: addget-api-container
  DEPLOYMENT_LABELS:
  - name: app
    value: addget-api
  NODEPORT_NAME: nodeport-addget-api
  NODEPORT_PORT: 8080
  NODEPORT_TARGET_PORT: 8080
  NODEPORT_NODEPORT: 30001
quotesapi:
  CLUSTER_IP_NAME: quotes-api #continuar
  CLUSTER_IP_PORT: 8080
  DEPLOYMENT_NAME: quotes-api-deployment
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_CONTAINER_PORT: 8080
  DEPLOYMENT_IMAGE_VERSION: "3.0"
  DEPLOYMENT_LABELS:
  - name: app
    value: quotes-api
mainpage:
  NODEPORT_NAME: nodeport-mainpage-api
  NODEPORT_PORT: 8080
  NODEPORT_TARGET_PORT: 8080
  NODEPORT_NODE_PORT: 30000
  DEPLOYMENT_NAME: mainpage-api-deployment
  DEPLOYMENT_CONTAINER_NAME: mainpage-api-container
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_IMAGE_VERSION: "1.0"
  DEPLOYMENT_CONTAINERPORT: 8080
  DEPLOYMENT_LABELS:
  - name: app
    value: mainpage-api
imagesapi:
  CLUSTER_IP_NAME: images-api #continuar
  CLUSTER_IP_PORT: 8080
  CLUSTER_IP_SELECTORS:
  - name: app
    value: images-api
  DEPLOYMENT_NAME: images-api-deployment
  DEPLOYMENT_REPLICAS: 1
  DEPLOYMENT_IMAGE_VERSION: "latest"
  DEPLOYMENT_PORT: 8080
  DEPLOYMENT_LABELS:
  - name: app
    value: image-api
  