apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.CLUSTER_IP_NAME }}
spec:
  type: ClusterIP
  selector:
    app: quotes-db
  ports:
    - port: {{ .Values.database.CLUSTER_IP_PORT }}