apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.CLUSTER_IP_NAME }}
spec:
  type: ClusterIP
  selector:
    {{- range .Values.database.CLUSTER_IP_DEPLOYMENT_LABELS }}
      {{ .name }}: {{ .value }}
    {{- end}}
  ports:
    - port: {{ .Values.database.CLUSTER_IP_PORT }}