apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imagesapi.CLUSTER_IP_NAME }}
spec:
  type: ClusterIP
  selector:
  {{- range .Values.imagesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
    {{ .name }}: {{ .value }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.imagesapi.CLUSTER_IP_PORT }}
      targetPort: {{ .Values.imagesapi.CLUSTER_IP_PORT }}