apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.quotesapi.CLUSTER_IP_NAME }}
spec:
  type: ClusterIP
  selector:
  {{- range .Values.quotesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
    {{ .name }}: {{ .value }}
  {{- end }}
  ports:
    - port: {{ .Values.quotesapi.CLUSTER_IP_PORT }}