apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mainpage.DEPLOYMENT_NAME }}
spec:
  replicas: {{ .Values.mainpage.DEPLOYMENT_REPLICAS }}
  selector:
    matchLabels:
    {{- range .Values.mainpage.DEPLOYMENT_LABELS }}
      {{ .name }}: {{ .value }}
    {{- end}}
  template:
    metadata:
      labels:
      {{- range .Values.mainpage.DEPLOYMENT_LABELS }}
        {{ .name }}: {{ .value }}
      {{- end}}
    spec:
      containers:
      - name: {{ .Values.mainpage.DEPLOYMENT_CONTAINER_NAME }}
        image: clusterminator/mainpage-api:{{ .Values.mainpage.DEPLOYMENT_IMAGE_VERSION }}
        ports:
        - containerPort: {{ .Values.mainpage.DEPLOYMENT_CONTAINERPORT }}
