apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.imagesapi.DEPLOYMENT_NAME }}
spec:
  replicas: {{ .Values.imagesapi.DEPLOYMENT_REPLICAS }}
  selector:
    matchLabels:
    {{- range .Values.imagesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
      {{ .name }}: {{ .value }}
    {{- end}}
  template:
    metadata:
      labels:
      {{- range .Values.imagesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
        {{ .name }}: {{ .value }}
      {{- end}}
    spec:
      containers:
      - name: images-api-container
        image: clusterminator/images-api:{{ .Values.imagesapi.DEPLOYMENT_IMAGE_VERSION }}
        ports:
        - containerPort: {{ .Values.imagesapi.DEPLOYMENT_PORT }}
