apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.quotesapi.DEPLOYMENT_NAME }}
spec:
  replicas: {{ .Values.quotesapi.DEPLOYMENT_REPLICAS }}
  selector:
    matchLabels:
    {{- range .Values.quotesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
      {{ .name }}: {{ .value }}
    {{- end}}
  template:
    metadata:
      labels:
      {{- range .Values.quotesapi.CLUSTER_IP_DEPLOYMENT_LABELS }}
        {{ .name }}: {{ .value }}
      {{- end}}
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'sleep 10']
      containers:
      - name: quotes-api-container
        image: clusterminator/quotes-api:{{ .Values.quotesapi.DEPLOYMENT_IMAGE_VERSION }}
        ports:
        - containerPort: {{ .Values.quotesapi.DEPLOYMENT_REPLICAS }}
        envFrom:
        - configMapRef:
            name: quotes-api-config
