apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.addget.DEPLOYMENT_NAME }}
spec:
  replicas: {{ .Values.addget.DEPLOYMENT_REPLICAS }}
  selector:
    matchLabels:
    {{- range .Values.addget.NODEPORT_DEPLOYMENT_LABELS }}
      {{ .name }}: {{ .value }}
    {{- end}}
  template:
    metadata:
      labels:
      {{- range .Values.addget.NODEPORT_DEPLOYMENT_LABELS }}
        {{ .name }}: {{ .value }}
      {{- end}}
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'sleep 10']
      containers:
      - name: {{ .Values.addget.DEPLOYMENT_CONTAINER_NAME }}
        image: clusterminator/addget-api:{{ .Values.addget.DEPLOYMENT_IMAGE_VERSION }}
        ports:
        - containerPort: {{ .Values.addget.DEPLOYMENT_CONTAINER_PORT }}
        envFrom:
        - configMapRef:
            name: quotes-api-config