apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.addget.NODEPORT_NAME }}
spec:
  type: NodePort
  selector:
    app: addget-api
  ports:
    - port: {{ .Values.addget.NODEPORT_PORT }}
      targetPort: {{ .Values.addget.NODEPORT_PORT }}
      nodePort: {{ .Values.addget.NODEPORT_NODEPORT }}