apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainpage.NODEPORT_NAME }}
spec:
  type: NodePort
  selector:
    app: mainpage-api
  ports:
    - port: {{ .Values.mainpage.NODEPORT_PORT }}
      targetPort: {{ .Values.mainpage.NODEPORT_PORT_TARGET }}
      nodePort: {{ .Values.mainpage.NODEPORT_NODE_PORT }}