apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.addget.NODEPORT_NAME }}
spec:
  type: NodePort
  selector:
    app: addget-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001