apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.QUOTES_DB_PVC_NAME }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.QUOTES_DB_PVC_STORAGE }}  # Mesmo que o PV