apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.database.QUOTES_DB_VOLUME_NAME }}
spec:
  capacity:
    storage: {{ .Values.database.QUOTES_DB_VOLUME_STORAGE }}  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/quotes-db  # Path on the host machine where the data will be stored
